[settings]
batchSize = 64
numEpochs = 30
architecture = 'FFN'

# define network architecture
# possible layer types are 'dense', 'lowRank', and 'vanillaLowRank', 'flatten',
# possible activations are 'relu', 'linear', 'sigmoid', 'tanh'

[[layer]]
type = 'flatten'

[[layer]]
type = 'dense'
dims = [784,128]
activation = 'relu'

[[layer]]
type = 'dense'
dims = [128, 64]
activation = 'relu'


[[layer]]
type = 'dense'
dims = [64, 10]
activation = 'linear'

[[layer]]
type = 'softmax'
dim = 1


# ---------- Optimizer Config --------------

[optimizer.default]
type = 'adam'
parameters = { lr = 0.005 }