[settings]
learningRate = 0.001
batchSize = 64
numEpochs = 10
architecture = 'FFN'

# define network architecture
# possible layer types are 'dense', 'lowRank', and 'vanillaLowRank'
# possible activations are 'relu', 'linear', 'sigmoid', 'tanh'

[[layer]]
type = 'lowRank'
dims = [784,512]
activation = 'relu'
rank = 20

[[layer]]
type = 'lowRank'
dims = [512, 256]
activation = 'relu'
rank = 20

[[layer]]
type = 'dense'
dims=[256,10]
activation = 'linear'